k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 7705c02a-f05f-597c-9c84-db860b9fbdb2
    cluster_name: Alejandro cluster
- manifest_path: /manifests
  cluster_info:
    cluster_id: 8333c8eb-9656-5b5c-bfc7-da1181879219
    cluster_name: Alejandro's cluster
