apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  rollout-demo-mapping
  namespace: 'playground'
spec:
  resolver: endpoint
  prefix: /rollout-demo
  rewrite: /echo
  service: rollout-demo:80
