apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 69d9f7c0-db30-4052-b91c-2e678d851414
  creationTimestamp: null
  name: rollout-demo
  namespace: playground
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollout-demo
  strategy:
    canary:
      canaryService: rollout-demo-canary
      stableService: rollout-demo
      steps:
      - setWeight: 20
      - pause:
          duration: 120
      - setWeight: 40
      - pause:
          duration: 120
      - setWeight: 60
      - pause:
          duration: 120
      - setWeight: 80
      - pause:
          duration: 120
      - setWeight: 100
      - pause:
          duration: 120
      trafficRouting:
        ambassador:
          mappings:
          - rollout-demo-mapping
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rollout-demo
    spec:
      containers:
      - args:
        - -text=VERSION 1
        - -listen=:8080
        image: hashicorp/http-echo:0.1.1
        imagePullPolicy: Always
        name: echo-v1
        ports:
        - containerPort: 8080
        resources: {}
status:
  blueGreen: {}
  canary: {}
